### ISSUE TITLE
Complete the Tic-Tac-Toe game

### ISSUE THREAD

**Issue by nuffQuantumSayd** [nuffQuantumSayd/TicTacToeApp#17]
The app allows the user to play a game of Tic-Tac-Toe
- [x] The user can click the New Game button any time to start a new game
- [x] When you press the New Game button, the board is cleared and it becomes X's turn
- [x] #18
- [x] When a button has a symbol on it, it is no longer possible to change it except through the new game button
- [x] #19
- [x] The only way to start a new game is through the new game button
